// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_De_Gestion.Models
{
    [Table("Table_Roles")]
    public partial class TableRole
    {
        public TableRole()
        {
            TablePermisos = new HashSet<TablePermiso>();
            TableUsuarios = new HashSet<TableUsuario>();
        }

        [Key]
        [Column("ID_Rol")]
        public int IdRol { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        [Column("ID_Usuario")]
        public int? IdUsuario { get; set; }

        [ForeignKey("IdUsuario")]
        [InverseProperty("TableRoles")]
        public virtual TableUsuario IdUsuarioNavigation { get; set; }
        [InverseProperty("IdRolNavigation")]
        public virtual ICollection<TablePermiso> TablePermisos { get; set; }
        [InverseProperty("IdRolNavigation")]
        public virtual ICollection<TableUsuario> TableUsuarios { get; set; }
    }
}