// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_De_Gestion.Models
{
    [Table("Table_Ventanas")]
    public partial class TableVentana
    {
        public TableVentana()
        {
            TableAcciones = new HashSet<TableAccione>();
        }

        [Key]
        [Column("ID_Ventana")]
        public int IdVentana { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }

        [InverseProperty("IdVentanaNavigation")]
        public virtual ICollection<TableAccione> TableAcciones { get; set; }
    }
}