// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_De_Gestion.Models
{
    [Table("Table_Sub_Tramite")]
    public partial class TableSubTramite
    {
        public TableSubTramite()
        {
            TableRelacionClienteTramites = new HashSet<TableRelacionClienteTramite>();
        }

        [Key]
        [Column("IDSubTramite")]
        public int IdsubTramite { get; set; }
        [Column("IDTramite")]
        public int Idtramite { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string TituloSubTramite { get; set; }
        [StringLength(150)]
        [Unicode(false)]
        public string DescripcionSubTramite { get; set; }
        public bool Habilitado { get; set; }
        [Column("Fecha_Alta", TypeName = "datetime")]
        public DateTime FechaAlta { get; set; }
        [Column("Fecha_Ult_Modificacion", TypeName = "datetime")]
        public DateTime FechaUltModificacion { get; set; }

        [ForeignKey("Idtramite")]
        [InverseProperty("TableSubTramites")]
        public virtual TableTipoTramite IdtramiteNavigation { get; set; }
        [InverseProperty("IdsubTramiteNavigation")]
        public virtual ICollection<TableRelacionClienteTramite> TableRelacionClienteTramites { get; set; }
    }
}