// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_De_Gestion.Models
{
    [Table("Table_Usuarios")]
    public partial class TableUsuario
    {
        public TableUsuario()
        {
            TableRoles = new HashSet<TableRole>();
        }

        [Key]
        [Column("ID_Usuario")]
        public int IdUsuario { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Usuario { get; set; }
        [Required]
        public byte[] Token { get; set; }
        [Required]
        public byte[] Pass { get; set; }
        [Column("ID_Telefono")]
        public int? IdTelefono { get; set; }
        [Column("ID_Correo")]
        public int? IdCorreo { get; set; }
        [Column("ID_Rol")]
        public int IdRol { get; set; }

        [ForeignKey("IdCorreo")]
        [InverseProperty("TableUsuarios")]
        public virtual TableCorreo IdCorreoNavigation { get; set; }
        [ForeignKey("IdRol")]
        [InverseProperty("TableUsuarios")]
        public virtual TableRole IdRolNavigation { get; set; }
        [ForeignKey("IdTelefono")]
        [InverseProperty("TableUsuarios")]
        public virtual TableTelefono IdTelefonoNavigation { get; set; }
        [InverseProperty("IdUsuarioNavigation")]
        public virtual ICollection<TableRole> TableRoles { get; set; }
    }
}