// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_De_Gestion.Models
{
    [Table("Table_Permisos")]
    public partial class TablePermiso
    {
        [Key]
        [Column("ID_Permiso")]
        public int IdPermiso { get; set; }
        [Column("ID_Rol")]
        public int IdRol { get; set; }
        [Column("ID_Accion")]
        public int IdAccion { get; set; }

        [ForeignKey("IdAccion")]
        [InverseProperty("TablePermisos")]
        public virtual TableAccione IdAccionNavigation { get; set; }
        [ForeignKey("IdRol")]
        [InverseProperty("TablePermisos")]
        public virtual TableRole IdRolNavigation { get; set; }
    }
}