// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_De_Gestion.Models
{
    [Table("Table_Correos")]
    public partial class TableCorreo
    {
        public TableCorreo()
        {
            TableUsuarios = new HashSet<TableUsuario>();
        }

        [Key]
        [Column("ID_Correo")]
        public int IdCorreo { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Correo { get; set; }
        [Required]
        [StringLength(150)]
        [Unicode(false)]
        public string Obs { get; set; }
        [Column("ID_Cliente")]
        public int IdCliente { get; set; }
        public bool Habilitado { get; set; }
        [Column("Fecha_Alta", TypeName = "datetime")]
        public DateTime FechaAlta { get; set; }
        [Column("Fecha_Ult_Modificacion", TypeName = "datetime")]
        public DateTime FechaUltModificacion { get; set; }

        [ForeignKey("IdCliente")]
        [InverseProperty("TableCorreos")]
        public virtual TableCliente IdClienteNavigation { get; set; }
        [InverseProperty("IdCorreoNavigation")]
        public virtual ICollection<TableUsuario> TableUsuarios { get; set; }
    }
}