// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_De_Gestion.Models
{
    [Table("Table_Acciones")]
    public partial class TableAccione
    {
        public TableAccione()
        {
            TablePermisos = new HashSet<TablePermiso>();
        }

        [Key]
        [Column("ID_Accion")]
        public int IdAccion { get; set; }
        [Required]
        [StringLength(150)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        [Column("ID_Ventana")]
        public int IdVentana { get; set; }

        [ForeignKey("IdVentana")]
        [InverseProperty("TableAcciones")]
        public virtual TableVentana IdVentanaNavigation { get; set; }
        [InverseProperty("IdAccionNavigation")]
        public virtual ICollection<TablePermiso> TablePermisos { get; set; }
    }
}