// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sistema_De_Gestion.Models
{
    [Table("Table_Relacion_Cliente_Tramites")]
    public partial class TableRelacionClienteTramite
    {
        [Key]
        [Column("IDRelacion")]
        public int Idrelacion { get; set; }
        [StringLength(1500)]
        [Unicode(false)]
        public string Descripcion { get; set; }
        [Column("IDSubTramite")]
        public int IdsubTramite { get; set; }
        [Column("ID_Cliente")]
        public int IdCliente { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Estado { get; set; }
        public bool Habilitado { get; set; }
        [Column("Fecha_Alta", TypeName = "datetime")]
        public DateTime FechaAlta { get; set; }
        [Column("Fecha_Ult_Modificacion", TypeName = "datetime")]
        public DateTime FechaUltModificacion { get; set; }

        [ForeignKey("IdCliente")]
        [InverseProperty("TableRelacionClienteTramites")]
        public virtual TableCliente IdClienteNavigation { get; set; }
        [ForeignKey("IdsubTramite")]
        [InverseProperty("TableRelacionClienteTramites")]
        public virtual TableSubTramite IdsubTramiteNavigation { get; set; }
    }
}