// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sistema_De_Gestion
{
    public partial class TableLog
    {
        public int IdLog { get; set; }
        public string Descripcion { get; set; }
        public string Usuario { get; set; }
        public string Obj { get; set; }
        public string Detaller { get; set; }
        public DateTime FechaLog { get; set; }
    }
}